services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: wedding-app
        depends_on:
            - db
        networks:
            - wedding

    db:
        image: postgres:latest
        container_name: wedding-db
        environment:
            POSTGRES_DB: wedding
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 12345678
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - wedding

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: wedding-nginx
        ports:
            - 8080:80
        networks:
            - wedding
        depends_on:
            - app

volumes:
    postgres_data:

networks:
    wedding:
        driver: bridge
