services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: wedding-app
        depends_on:
            - db
        networks:
            - wedding

    db:
        image: postgres:latest
        container_name: wedding-db
        environment:
            POSTGRES_DB: wedding
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 12358132134
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            #- ./postgres_conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
            #- ./postgres_conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
        networks:
            - wedding

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: wedding-nginx
        ports:
            - 8000:80
        networks:
            - wedding
        depends_on:
            - app

volumes:
    postgres_data:

networks:
    wedding:
        driver: bridge
